### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by meteor-ec**

### CODE REVIEW

**Comment by spraguex** [comment]
Hey I want to thank you for all the work you do on this plugin! I have over 60 customers that use it and it's the Bedrock of my business. Would you mind having a look at this screencast as to a problem I have noticed over the last several versions? Thanks! - Josh
https://drive.google.com/file/d/1I32bM0yMlj_5j1tMi2AgwggC4Jk5aZUC/view

**Comment by meteor-ec** [comment]
Hi @spraguex,

This is Ilnur from Ecwid by Lightspeed team. 

Thank you for reporting this issue! We will look into it.

Regards,

**Comment by meteor-ec** [comment]
Hi @spraguex 

We’ve released a fix for this issue in version 6.12.25. Please feel free to update your plugin.

Thank you for your patience!

**Comment by spraguex** [comment]
Man that is just perfect!  Thank you so much for your great work on this plugin! How can I buy you a coffee!?

**Comment by meteor-ec** [comment]
@spraguex Thanks for the kind words! I would be grateful if you could leave your feedback on our plugin page https://wordpress.org/support/plugin/ecwid-shopping-cart/reviews/?filter=5 :handshake:

**Comment by spraguex** [comment]
Done!  Thanks again for all the help on this.

**Comment by meteor-ec** [comment]
Thank you so much!

You mentioned that you use Avada. Could you please share your ideas or problems you face when using Ecwid and Avada? You can write to me at meteor@ecwid.com

This will be valuable for us as well.

Thank you!

**Pull request merged**
